# Parameters for point cloud conversion node
# it converts a sensor_msgs/PointCloud2 to a rmcl_msgs/O1DnStamped
# simple fitering can be achieved by skipping rows or cols
rmcl_scan_to_scan:
  ros__parameters:
    debug_cloud: True
    # filter / pre-processing:
    skip_begin: 0
    skip_end: 0
    increment: 2