# Parameters for point cloud conversion node
# it converts a sensor_msgs/PointCloud2 to a rmcl_msgs/O1DnStamped
# simple fitering can be achieved by skipping rows or cols
rmcl_lidar2d_conversion:
  ros__parameters:
    use_sim_time: True
    debug_cloud: True
    # filter / pre-processing:
    skip_begin: 0
    skip_end: 0
    increment: 1

# Parameters for the MICP-L node
micp_localization:
  ros__parameters:
    use_sim_time: True

    # required frames
    base_frame: base_footprint
    odom_frame: odom
    map_frame: map

    # maximum number of correction steps per second
    # lower this to decrease the correction speed but save energy 
    disable_correction: False
    correction_rate_max: 5.0
    optimization_iterations: 1
    tf_time_source: 1 # 0: measurement_latest, 1: correction_latest
    tf_rate: 100.0
    broadcast_tf: True
    publish_pose: True
    pose_noise: 0.01 # minimum noise of pose. can be set from sensor noise

    # adjust max distance dependent of the state of localization
    adaptive_max_dist: True # enable adaptive max dist

    # initial pose changes
    initial_pose_offset: [0.0, 0.0, 2.0, 0.0, 0.0, 0.0] # translation + euler angles (6) or translation + quaternion (7)

    # describe your sensor setup here
    sensors: # list of range sensors - at least one is required
      lidar2d:
        data_source: topic
        model_type: spherical
        topic_name: /rmcl_inputs/lidar2d
        correspondences:
          backend: embree
          type: RC
          adaptive_max_dist_min: 0.5
          max_dist: 2.0
          visualize: True