rmcl_conversion:
  ros__parameters:
    use_sim_time: True
    debug_cloud: True
    width:
      skip_begin: 0 # skip elements from begin  
      skip_end:   0 # skip elements from end
      increment:  4 # increment to skip data. Simple filter to reduce scan density
    height:
      skip_begin: 0 # cutting height from begin
      skip_end:   0 # cutting height from end
      increment:  1 # increment to skip data. Simple filter to reduce scan density 
    model:
      range_min: 0.3
      range_max: 80.0
